### ISSUE TITLE
Home (Bitmon catalogue) Page

### ISSUE THREAD

**Issue by 0xPasho** [bitmonspace/marketspace#2]
### General expected funcionality
We need to make the home screen page. In it we should display all bitmons with their price, every bitmon should send you into his page with his details. This page also has a section to filter bitmons.

### Tasks
- [ ] Display bitmons.
- [ ] Filter to display bitmons.
- [ ] Like button on every bitmon.
- [ ] On press a bitmon we should see their information.
