### ISSUE TITLE
User(Profile) Page

### ISSUE THREAD

**Issue by 0xPasho** [bitmonspace/marketspace#4]
### General expected funcionality
We need to implement a page for users to be able to see their information related to collected NFTs, account information and transactions history.

### Tasks
- [ ] Settings button to send to account settings screen.
- [ ] Share button
- [ ] Creation of tabs to classify: My Bitmons, Favorites, History, Offers
- [ ] *My Bitmons tab* should display all the bitmons related to that user.
- [ ] *Favorites* should display the list of things that this user liked.
- [ ] *History* should display the transaction history of this user.
- [ ] *Offers* should display display the list of offer made or received.
