### ISSUE TITLE
Bitmon details Page

### ISSUE THREAD

**Issue by 0xPasho** [bitmonspace/marketspace#5]
### General expected funcionality
We need to make the bitmon details page. In it we should display all the information related to a bitmon.

### Tasks
- [ ] Display bitmon(image, video, gif).
- [ ] Display all important information related to bitmon
- [ ] Display information of the owner
- [ ] Display transaction history of bitmon.
- [ ] Offer action button.
- [ ] Like button
- [ ] Display bitmons offspring.
