### ISSUE TITLE
Settings screen

### ISSUE THREAD

**Issue by 0xPasho** [bitmonspace/marketspace#7]
### General expected funcionality
We need to make the a settings page to let users configure their site appereance and profile information.

### Tasks
- [ ] We should have the nexts tabs in it: Profile, Appearance and Support.
- [ ] *Profile tab*, we display in there the username, email address and wallet address, letting users modify it.
- [ ] *Appearance tab*, we display the current theme and current language, letting users modify it.
- [ ] *Support tab*, we display information that can be useful to the user.
